FROM python:3.11-slim

WORKDIR /backend

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    wget unzip gnupg curl ca-certificates lsb-release fonts-liberation \
    libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 \
    libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 xdg-utils \
    chromium-driver \
    --no-install-recommends && rm -rf /var/lib/apt/lists/*

# Instalar dependencias de Python
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html

# Copiar el resto de los archivos
COPY . .

EXPOSE 8004

ENTRYPOINT ["uvicorn", "src.server:app", "--host", "0.0.0.0", "--port", "8004"]

